import { lazy, Suspense, useEffect, useMemo, useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, BadgeDollarSign, CircleDollarSign, Compass, Goal, Plus, Sparkles, Wallet2, BadgeCheck, CircleEllipsis, Target, TrendingUp, TrendingDown, CircleDashed } from 'lucide-react'
import { useFinance } from '../context/FinanceContext.jsx'
import TransactionDialog from '../components/transaction/TransactionDialog.jsx'
import AccountDialog from '../components/account/AccountDialog.jsx'
import { dateLabel, formatMoney } from '../utils/formatters.js'
import { useAuth } from '../context/AuthContext.jsx'

const Charts = lazy(() => import('../components/charts/DashboardCharts.jsx'))
const iconFor = category => ({ Food: <BadgeDollarSign size={18} />, 'Food & Dining': <BadgeDollarSign size={18} />, Travel: <Compass size={18} />, Transport: <Wallet2 size={18} />, Shopping: <Sparkles size={18} />, Bills: <CircleDollarSign size={18} />, Fuel: <CircleDollarSign size={18} />, Entertainment: <CircleEllipsis size={18} />, Health: <BadgeCheck size={18} /> }[category] || <CircleDashed size={18} />)

function CountUp({ value, format = formatMoney }) {
  const [display, setDisplay] = useState(0)
  useEffect(() => { let frame; const start = performance.now(); const duration = 700; const target = Number(value) || 0; const tick = now => { const elapsed = Math.min(1, (now - start) / duration); setDisplay(target * (1 - Math.pow(1 - elapsed, 3))); if (elapsed < 1) frame = requestAnimationFrame(tick) }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame) }, [value])
  return <>{format(display)}</>
}

function Snapshot({ icon, label, value, tone = 'neutral', trend }) { return <article className={`snapshot-card ${tone}`}><span className="snapshot-icon" aria-hidden="true">{icon}</span><span>{label}</span><b><CountUp value={value} /></b><small>{trend}</small></article> }

export default function Dashboard() {
  const { user } = useAuth()
  const { expenses: transactions, accounts, budgets, goals, rawCategories, addAccount, loading, error } = useFinance()
  const [dialog, setDialog] = useState(null)
  const [notice, setNotice] = useState('')
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 3500); return () => clearTimeout(timer) }, [notice])
  const now = new Date(); const month = now.toISOString().slice(0, 7)
  const overview = useMemo(() => {
    const monthTransactions = transactions.filter(x => x.date.startsWith(month)); const income = monthTransactions.filter(x => x.transactionType === 'income').reduce((sum, x) => sum + Number(x.amount), 0); const expense = monthTransactions.filter(x => x.transactionType === 'expense').reduce((sum, x) => sum + Number(x.amount), 0); const balance = accounts.filter(x => x.is_active).reduce((sum, x) => sum + Number(x.current_balance), 0); const opening = accounts.filter(x => x.is_active).reduce((sum, x) => sum + Number(x.opening_balance), 0); const budget = budgets.filter(x => x.month.startsWith(month) && x.period === 'monthly').reduce((sum, x) => sum + Number(x.monthly_limit), 0); return { income, expense, balance, growth: balance - opening, savings: income - expense, budgetRemaining: budget - expense, budget } }, [accounts, budgets, month, transactions])
  const months = useMemo(() => Array.from({ length: 12 }, (_, i) => { const d = new Date(); d.setMonth(d.getMonth() - 11 + i); const key = d.toISOString().slice(0, 7); const xs = transactions.filter(x => x.date.startsWith(key)); return { label: d.toLocaleDateString('en', { month: 'short' }), income: xs.filter(x => x.transactionType === 'income').reduce((s, x) => s + x.amount, 0), expense: xs.filter(x => x.transactionType === 'expense').reduce((s, x) => s + x.amount, 0) } }), [transactions])
  const categoryData = useMemo(() => Object.entries(transactions.filter(x => x.transactionType === 'expense').reduce((m, x) => ({ ...m, [x.category]: (m[x.category] || 0) + x.amount }), {})).map(([label, value]) => ({ label, value })), [transactions])
  const accountData = accounts.map(x => ({ label: x.name, value: Math.abs(Number(x.current_balance)) }))
  const budgetRows = budgets.filter(x => x.month.startsWith(month) && x.period === 'monthly').slice(0, 3).map((item, index) => { const category = rawCategories.find(x => x.id === item.category_id)?.name || item.name || 'Monthly budget'; const spent = transactions.filter(x => x.transactionType === 'expense' && x.category === category && x.date.startsWith(month)).reduce((sum, x) => sum + Number(x.amount), 0); const limit = Number(item.monthly_limit) + Number(item.carry_forward || 0); return { id: item.id || index, category, spent, limit, percentage: Math.min(100, limit ? spent / limit * 100 : 0) } })
  const save = async x => { try { await addAccount(x); setDialog(null) } catch {} }
  const greeting = now.getHours() < 12 ? 'Good Morning,' : now.getHours() < 18 ? 'Good Afternoon,' : 'Good Evening,'
  if (loading) return <div className="dashboard-skeleton"><i/><i/><i/><i/></div>
  return <section className="dashboard premium-dashboard">{error && <p className="form-error">{error}</p>}{notice && <div className="snackbar" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss">×</button></div>}
    <header className="dashboard-greeting"><div><p>{greeting}</p><h1>{user?.user_metadata?.full_name || user?.full_name || user?.name || 'Welcome back'}</h1><span>{now.toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' })}</span></div><button className="account-shortcut text-button" onClick={() => setDialog({ kind: 'account' })}><Plus size={16} />Account</button></header>
    <section className="balance-hero"><div className="balance-aurora"/><div className="balance-copy"><p>Current balance</p><h2><CountUp value={overview.balance} /></h2><span className={overview.growth >= 0 ? 'positive-growth' : 'negative-growth'}>{overview.growth >= 0 ? <TrendingUp size={16} /> : <TrendingDown size={16} />} <CountUp value={Math.abs(overview.growth)} /> <em>monthly growth</em></span></div><div className="balance-orbit" aria-hidden="true"><span>₹</span></div></section>
    <section className="snapshot-grid" aria-label="Financial snapshots"><Snapshot icon={<ArrowUpRight size={18} />} label="Income" value={overview.income} tone="success" trend="This month"/><Snapshot icon={<ArrowDownLeft size={18} />} label="Expense" value={overview.expense} tone="expense" trend="This month"/><Snapshot icon={<Target size={18} />} label="Savings" value={overview.savings} tone="savings" trend={overview.savings >= 0 ? 'On track' : 'Review spending'}/><Snapshot icon={<Goal size={18} />} label="Budget remaining" value={overview.budgetRemaining} tone="budget" trend={overview.budget ? `${Math.round(Math.max(0, overview.budgetRemaining) / overview.budget * 100)}% available` : 'No monthly budget'}/></section>
    <section className="dashboard-section"><div className="section-heading"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Move money with ease</h2></div></div><div className="premium-actions"><button onClick={() => setDialog({ kind: 'transaction', transactionType: 'expense' })}><i><ArrowDownLeft size={16} /></i><span>Add Expense</span></button><button onClick={() => setDialog({ kind: 'transaction', transactionType: 'income' })}><i><ArrowUpRight size={16} /></i><span>Add Income</span></button><button onClick={() => setDialog({ kind: 'transaction', transactionType: 'transfer' })}><i><CircleEllipsis size={16} /></i><span>Transfer</span></button><a href="#budget-progress"><i><CircleDollarSign size={16} /></i><span>Budget</span></a><a href="#goals"><i><Target size={16} /></i><span>Goals</span></a></div></section>
    <div className="dashboard-content-grid"><section className="card premium-recent"><div className="section-heading"><div><p className="eyebrow">ACTIVITY</p><h2>Recent transactions</h2></div><span>Last 5</span></div>{transactions.length ? transactions.slice(0, 5).map(t => <article className="premium-transaction" key={t.id}><span className={`transaction-avatar ${t.transactionType}`} aria-hidden="true">{iconFor(t.category)}</span><div><b>{t.merchant || t.title}</b><small>{dateLabel(t.date)} · {accounts.find(x => x.id === t.accountId)?.name || 'No account'}</small></div><strong className={t.transactionType === 'income' ? 'income' : t.transactionType === 'transfer' ? 'transfer' : 'negative'}>{t.transactionType === 'income' ? '+' : '−'}{formatMoney(t.amount)}</strong></article>) : <div className="dashboard-empty"><span><CircleDashed size={20} /></span><b>Your activity will appear here</b><p>Add your first transaction to see your spending story.</p><button className="primary" onClick={() => setDialog({ kind: 'transaction', transactionType: 'expense' })}>Add expense</button></div>}</section>
      <section className="card budget-progress-card" id="budget-progress"><div className="section-heading"><div><p className="eyebrow">BUDGETS</p><h2>Monthly progress</h2></div><span>{formatMoney(Math.max(0, overview.budgetRemaining))} left</span></div>{budgetRows.length ? budgetRows.map((item, index) => <article className="budget-progress-row" key={item.id}><div><b>{item.category}</b><small>{formatMoney(item.limit - item.spent)} remaining</small></div><strong>{Math.round(item.percentage)}%</strong><div className={`budget-progress-fill fill-${index}`}><i style={{ width: `${item.percentage}%` }}/></div></article>) : <div className="dashboard-empty compact"><span><CircleDollarSign size={18} /></span><b>No monthly budget yet</b><p>Set a budget to follow your progress here.</p></div>}</section></div>
    <section className="goal-section" id="goals"><div className="section-heading"><div><p className="eyebrow">GOALS</p><h2>Future, funded</h2></div><span>{goals.length} active</span></div><div className="premium-goal-grid">{goals.length ? goals.slice(0, 3).map((goal, index) => { const progress = Math.min(100, Number(goal.current_amount) / Number(goal.goal_amount) * 100); const remaining = Math.max(0, Number(goal.goal_amount) - Number(goal.current_amount)); return <article className="premium-goal-card" key={goal.id}><div className={`goal-progress-ring ring-${index}`} style={{ '--progress': `${progress * 3.6}deg` }}><b>{Math.round(progress)}%</b></div><div><b>{goal.name}</b><small>Target {goal.target_date ? dateLabel(goal.target_date) : 'not set'}</small><strong>{formatMoney(remaining)} <span>to go</span></strong><p>{goal.monthly_contribution ? `${formatMoney(goal.monthly_contribution)} monthly contribution` : 'Set a monthly contribution'}</p></div></article> }) : <article className="dashboard-empty goal-empty"><span><Target size={20} /></span><b>Make a goal feel closer</b><p>Create a goal to track each milestone here.</p></article>}</div></section>
    <Suspense fallback={<div className="dashboard-skeleton charts"><i/><i/></div>}><Charts categoryData={categoryData} accountData={accountData} months={months}/></Suspense>
    {dialog?.kind === 'transaction' && <TransactionDialog transaction={dialog.id ? dialog : { transactionType: dialog.transactionType }} onClose={() => setDialog(null)} onSuccess={setNotice} />}{dialog?.kind === 'account' && <AccountDialog onSave={save} onClose={() => setDialog(null)} />}
  </section>
}
