import { useMemo } from 'react'
import { formatMoney } from '../../utils/formatters.js'

const clamp = value => Math.max(0, Math.min(100, value))

export default function FinancialHealth({ transactions, accounts, budgets, goals }) {
  const data = useMemo(() => {
    const now = new Date(); const month = now.toISOString().slice(0, 7); const today = now.getDate(); const monthDays = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()
    const monthTransactions = transactions.filter(item => item.date.startsWith(month)); const income = monthTransactions.filter(item => item.transactionType === 'income').reduce((sum, item) => sum + item.amount, 0); const expense = monthTransactions.filter(item => item.transactionType === 'expense').reduce((sum, item) => sum + item.amount, 0); const net = income - expense
    const budget = budgets.filter(item => item.month.startsWith(month) && item.period === 'monthly').reduce((sum, item) => sum + Number(item.monthly_limit), 0); const monthlyBurn = expense / Math.max(today, 1) * monthDays; const emergency = goals.filter(item => item.category === 'Emergency Fund').reduce((sum, item) => sum + Number(item.current_amount), 0); const coverage = monthlyBurn ? emergency / monthlyBurn : 0
    const goalProgress = goals.length ? goals.reduce((sum, item) => sum + Math.min(100, item.current_amount / item.goal_amount * 100), 0) / goals.length : 0
    const monthlyIncome = Array.from({ length: 3 }, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - index); const key = date.toISOString().slice(0, 7); return transactions.filter(item => item.date.startsWith(key) && item.transactionType === 'income').reduce((sum, item) => sum + item.amount, 0) }); const averageIncome = monthlyIncome.reduce((sum, value) => sum + value, 0) / 3; const stability = averageIncome ? clamp(100 - (Math.max(...monthlyIncome) - Math.min(...monthlyIncome)) / averageIncome * 100) : 0
    const savingsRate = income ? net / income * 100 : 0; const utilization = budget ? expense / budget * 100 : 0; const score = Math.round(clamp(savingsRate) * .25 + clamp(100 - utilization) * .2 + (net >= 0 ? 100 : 0) * .15 + clamp(coverage / 3 * 100) * .15 + goalProgress * .15 + stability * .1)
    const current = accounts.filter(item => item.is_active).reduce((sum, item) => sum + Number(item.current_balance), 0); const opening = accounts.filter(item => item.is_active).reduce((sum, item) => sum + Number(item.opening_balance), 0)
    return { score, savingsRate, utilization, monthlyBurn, coverage, goalProgress, net, netWorthGrowth: current - opening, projectedBalance: current + net / Math.max(today, 1) * (monthDays - today), expectedSavings: net / Math.max(today, 1) * monthDays, overspend: Math.max(0, expense / Math.max(today, 1) * monthDays - budget), hasGoals: goals.length > 0, alerts: [utilization >= 90 && 'Budget spending exceeds 90%.', net < 0 && 'Cash flow is negative.', coverage < 3 && 'Emergency fund is below 3 months of burn rate.', savingsRate < 20 && 'Savings rate is below the 20% target.'].filter(Boolean) }
  }, [transactions, accounts, budgets, goals])
  return <section className="health-section"><div className="health-hero"><div className="score-ring" style={{ '--score': `${data.score * 3.6}deg` }}><div><b>{data.score}</b><span>/100</span></div></div><div><p className="eyebrow">FINANCIAL HEALTH SCORE</p><h2>{data.score >= 80 ? 'Excellent shape' : data.score >= 60 ? 'On a solid path' : 'Needs attention'}</h2><p>Your score blends savings, budgets, cash flow, emergency coverage, goals, and income stability.</p></div></div><div className="health-kpis"><K label="Net worth growth" value={formatMoney(data.netWorthGrowth)} /><K label="Savings rate" value={`${Math.round(data.savingsRate)}%`} /><K label="Budget efficiency" value={`${Math.max(0, 100 - Math.round(data.utilization))}%`} /><K label="Monthly burn rate" value={formatMoney(data.monthlyBurn)} /><K label="Cash flow" value={formatMoney(data.net)} /><K label="Emergency coverage" value={`${data.coverage.toFixed(1)} months`} /><K label="Goal completion" value={`${Math.round(data.goalProgress)}%`} /></div><div className="forecast-grid"><K label="Projected month-end balance" value={formatMoney(data.projectedBalance)} /><K label="Expected savings" value={formatMoney(data.expectedSavings)} /><K label="Projected budget overspend" value={formatMoney(data.overspend)} /><K label="Goal completion forecast" value={data.hasGoals ? 'On track' : 'Add a goal'} /></div>{data.alerts.length > 0 && <div className="risk-alerts"><b>Risk alerts</b>{data.alerts.map(alert => <p key={alert}>⚠ {alert}</p>)}</div>}</section>
}
function K({ label, value }) { return <article><span>{label}</span><b>{value}</b></article> }
