import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { useAuth } from './AuthContext.jsx'
import { categories as defaults } from '../data/seed.js'
import { listCategories, createCategory } from '../supabase/categories.js'
import { listTransactions, createTransaction, updateTransaction, deleteTransaction, createTransfer } from '../supabase/transactions.js'
import { listBudgets, saveBudget, deleteBudget } from '../supabase/budgets.js'
import { listAccounts, createAccount, updateAccount, deleteAccount } from '../supabase/accounts.js'
import { listGoals, createGoal, updateGoal, deleteGoal, addContribution } from '../supabase/goals.js'
const FinanceContext = createContext(null)
const monthStart = () => `${new Date().toISOString().slice(0, 7)}-01`
export function FinanceProvider({ children }) { const { session, user } = useAuth(); const [expenses, setExpenses] = useState([]); const [categories, setCategories] = useState([]); const [accounts, setAccounts] = useState([]); const [goals, setGoals] = useState([]); const [budget, setBudgetState] = useState(0); const [budgets, setBudgets] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const token = session?.access_token
  useEffect(() => { if (!token) return; let active = true; setLoading(true); Promise.all([listTransactions(token), listCategories(token), listBudgets(token), listAccounts(token), listGoals(token)]).then(([txs,cats,loadedBudgets,loadedAccounts,loadedGoals]) => { if (!active) return; setExpenses(txs); setCategories(cats); setBudgets(loadedBudgets); setAccounts(loadedAccounts); setGoals(loadedGoals); setBudgetState(loadedBudgets.filter(x => x.month === monthStart() && x.period === 'monthly').reduce((sum, x) => sum + Number(x.monthly_limit), 0)); }).catch(e => active && setError(e.message)).finally(() => active && setLoading(false)); return () => { active = false } }, [token])
  const categoryNames = useMemo(() => [...new Set([...defaults, ...categories.filter(x => x.type === 'expense').map(x => x.name)])], [categories])
  const resolveCategory = async name => { let category = categories.find(x => x.name === name && x.type === 'expense'); if (!category) { category = await createCategory(token, { user_id: user.id, name, type: 'expense', icon: 'circle', color: '#10B981' }); setCategories(items => [...items, category]) } return category.id }
  const run = async work => { setError(''); try { return await work() } catch (e) { setError(e.message); throw e } }
  const reloadTransactions = async () => { const next = await listTransactions(token); setExpenses(next); const latestAccounts = await listAccounts(token); setAccounts(latestAccounts); return next }
  const addExpense = data => run(async () => { const categoryId = await resolveCategory(data.category); const next = await createTransaction(token, { user_id: user.id, category_id: categoryId, account_id: data.accountId || null, amount: data.amount, transaction_type: data.transactionType || 'expense', notes: data.note || data.title, merchant: data.merchant || null, tags: data.tags || [], payment_method: data.paymentMethod || null, receipt_path: data.receiptPath || null, recurring_frequency: data.recurringFrequency || null, date: data.date, time: data.time || null }); await reloadTransactions(); return next })
  const updateExpense = data => run(async () => { const categoryId = await resolveCategory(data.category); const next = await updateTransaction(token, data.id, { category_id: categoryId, account_id: data.accountId || null, amount: data.amount, transaction_type: data.transactionType || 'expense', notes: data.note || data.title, merchant: data.merchant || null, tags: data.tags || [], payment_method: data.paymentMethod || null, receipt_path: data.receiptPath || null, recurring_frequency: data.recurringFrequency || null, date: data.date, time: data.time || null }); await reloadTransactions(); return next })
  const removeExpense = id => run(async () => { await deleteTransaction(token, id); setExpenses(items => items.filter(x => x.id !== id)) })
  const moveCategory = (ids, category) => run(async () => { const categoryId = await resolveCategory(category); await Promise.all(ids.map(id => updateTransaction(token, id, { category_id: categoryId }))); await reloadTransactions() })
  const addTransfer = transfer => run(async () => { await createTransfer(token, { p_source_account: transfer.sourceAccountId, p_destination_account: transfer.destinationAccountId, p_amount: Number(transfer.amount), p_date: transfer.date, p_time: transfer.time || null, p_notes: transfer.note || null }); await reloadTransactions(); })
  const setBudget = amount => run(async () => { const overall = await resolveCategory('Overall budget'); const saved = await saveBudget(token, { user_id: user.id, category_id: overall, monthly_limit: Number(amount), month: monthStart(), period: 'monthly' }); setBudgetState(Number(saved.monthly_limit)); setBudgets(items => [...items.filter(x => !(x.category_id === overall && x.month === monthStart() && x.period === 'monthly')), saved]); return saved })
  const saveBudgetRecord = record => run(async () => { const categoryId = await resolveCategory(record.category); const saved = await saveBudget(token, { user_id: user.id, category_id: categoryId, monthly_limit: Number(record.monthly_limit), month: record.month, period: record.period, name: record.name || null, rollover_enabled: record.rollover_enabled, carry_forward: Number(record.carry_forward || 0), template_name: record.template_name || null }); setBudgets(items => [...items.filter(x => !(x.category_id === saved.category_id && x.month === saved.month && x.period === saved.period)), saved]); return saved })
  const removeBudget = id => run(async () => { await deleteBudget(token, id); setBudgets(items => items.filter(x => x.id !== id)) })
  const addAccount = account => run(async () => { const next = await createAccount(token, { ...account, user_id: user.id }); setAccounts(items => [next, ...items]); return next })
  const updateAccountRecord = account => run(async () => { const { id, user_id, created_at, ...changes } = account; const next = await updateAccount(token, id, changes); setAccounts(items => items.map(x => x.id === id ? next : x)); return next })
  const removeAccount = id => run(async () => { await deleteAccount(token, id); setAccounts(items => items.filter(x => x.id !== id)) })
  const addGoal = goal => run(async()=>{const next=await createGoal(token,{...goal,user_id:user.id});setGoals(x=>[next,...x]);return next})
  const updateGoalRecord = goal => run(async()=>{const {id,user_id,created_at,...data}=goal;const next=await updateGoal(token,id,data);setGoals(x=>x.map(g=>g.id===id?next:g));return next})
  const removeGoal = id => run(async()=>{await deleteGoal(token,id);setGoals(x=>x.filter(g=>g.id!==id))})
  const contributeToGoal = (id,amount,note) => run(async()=>{const next=await addContribution(token,id,amount,note);setGoals(x=>x.map(g=>g.id===id?next:g));return next})
  return <FinanceContext.Provider value={{ expenses, categories: categoryNames, rawCategories: categories, accounts, goals, budgets, budget, setBudget, saveBudgetRecord, deleteBudget: removeBudget, addExpense, updateExpense, deleteExpense: removeExpense, moveCategory, addTransfer, reloadTransactions, addAccount, updateAccount: updateAccountRecord, deleteAccount: removeAccount, addGoal, updateGoal: updateGoalRecord, deleteGoal: removeGoal, contributeToGoal, loading, error }}>{children}</FinanceContext.Provider> }
export const useFinance = () => useContext(FinanceContext)
