import { useMemo, useState } from 'react'
import { useFinance } from '../../context/FinanceContext.jsx'
import { useAuth } from '../../context/AuthContext.jsx'
import { supabaseUpload } from '../../supabase/client.js'

const methods = ['Cash', 'UPI', 'Credit Card', 'Card', 'Bank transfer', 'Cheque', 'Other']
const today = () => new Date().toISOString().slice(0, 10)
const formatAmount = value => value === '' ? '' : new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 }).format(Number(value))
const cleanAmount = value => { const next = value.replace(/[^0-9.]/g, ''); const [whole = '', ...decimal] = next.split('.'); return decimal.length ? `${whole}.${decimal.join('').slice(0, 2)}` : whole }
const latestExpense = expenses => [...expenses].filter(x => x.transactionType === 'expense').sort((a, b) => new Date(`${b.date}T${b.time || '00:00'}`) - new Date(`${a.date}T${a.time || '00:00'}`))[0]
const defaultMethod = account => account?.type === 'Cash' ? 'Cash' : account?.type === 'Credit Card' ? 'Credit Card' : 'UPI'

export default function TransactionDialog({ transaction, onClose, onSuccess }) {
  const { accounts, categories, expenses, addExpense, updateExpense, addTransfer } = useFinance()
  const { session, user } = useAuth()
  const activeAccounts = accounts.filter(x => x.is_active)
  const last = latestExpense(expenses)
  const defaultAccount = activeAccounts.find(x => x.id === last?.accountId) || activeAccounts[0]
  const [form, setForm] = useState(() => ({ transactionType: 'expense', amount: '', accountId: defaultAccount?.id || '', destinationAccountId: '', category: last?.category || categories[0] || 'Other', date: today(), time: new Date().toTimeString().slice(0, 5), merchant: '', location: '', note: '', tags: '', paymentMethod: defaultMethod(defaultAccount), recurringFrequency: '', receiptPath: '', ...transaction }))
  const [saving, setSaving] = useState(false)
  const [formError, setFormError] = useState('')
  const [moreDetails, setMoreDetails] = useState(false)
  const selectedAccount = activeAccounts.find(x => x.id === form.accountId)
  const quickCategories = useMemo(() => { const counts = expenses.filter(x => x.transactionType === 'expense').reduce((all, x) => ({ ...all, [x.category]: (all[x.category] || 0) + 1 }), {}); return [...new Set([...Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([name]) => name), 'Food', 'Travel', 'Shopping', 'Bills', 'Fuel', ...categories])].slice(0, 5) }, [categories, expenses])
  const update = e => setForm(x => ({ ...x, [e.target.name]: e.target.value }))
  const changeAccount = e => { const account = activeAccounts.find(x => x.id === e.target.value); setForm(x => ({ ...x, accountId: e.target.value, paymentMethod: defaultMethod(account) })) }
  const submit = async e => { e.preventDefault(); setFormError(''); if (Number(form.amount) <= 0) return setFormError('Enter an amount greater than zero.'); if (form.transactionType === 'transfer' && (!form.accountId || !form.destinationAccountId || form.accountId === form.destinationAccountId)) return setFormError('Choose two different accounts for the transfer.'); if (form.transactionType !== 'transfer' && !form.accountId) return setFormError('Choose an account.'); setSaving(true); try { if (form.transactionType === 'transfer') await addTransfer({ ...form, sourceAccountId: form.accountId }); else { const data = { ...form, title: form.merchant || form.note || form.category, tags: (Array.isArray(form.tags) ? form.tags.join(',') : form.tags).split(',').map(x => x.trim()).filter(Boolean) }; transaction?.id ? await updateExpense({ ...data, id: transaction.id }) : await addExpense(data) } onSuccess?.(form.transactionType === 'expense' && !transaction?.id ? 'Expense Added Successfully' : 'Transaction saved successfully'); onClose() } catch (err) { setFormError(err.message) } finally { setSaving(false) } }
  const upload = async e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) return setFormError('Receipt images must be 5 MB or smaller.'); setSaving(true); try { const path = `${user.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; await supabaseUpload(path, file, session.access_token); setForm(x => ({ ...x, receiptPath: path })) } catch (err) { setFormError(err.message) } finally { setSaving(false) } }
  const isTransfer = form.transactionType === 'transfer'
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal transaction-sheet" onSubmit={submit} onMouseDown={e => e.stopPropagation()}>
    <div className="modal-title"><div><p className="eyebrow">{transaction?.id ? 'UPDATE' : 'NEW TRANSACTION'}</p><h2>{transaction?.id ? 'Edit transaction' : isTransfer ? 'Transfer money' : form.transactionType === 'income' ? 'Add income' : 'Add expense'}</h2></div><button type="button" onClick={onClose} aria-label="Close">×</button></div>
    <div className="type-toggle">{['expense', 'income', 'transfer'].map(type => <button type="button" className={form.transactionType === type ? `type-${type}` : ''} key={type} onClick={() => setForm(x => ({ ...x, transactionType: type }))}>{type}</button>)}</div>
    <div className="two-col transaction-primary-fields"><label>Date<input required type="date" name="date" value={form.date} onChange={update} /></label><label className="amount-field">Amount<span className="amount-input"><b>₹</b><input required autoFocus inputMode="decimal" aria-label="Amount" type="text" name="amount" value={formatAmount(form.amount)} onChange={e => setForm(x => ({ ...x, amount: cleanAmount(e.target.value) }))} placeholder="0" /></span></label></div>
    <label>{isTransfer ? 'From account' : 'Account'}<select required name="accountId" value={form.accountId || ''} onChange={changeAccount}><option value="">Select account</option>{activeAccounts.map(x => <option key={x.id} value={x.id}>{x.icon} {x.name} · ₹{Number(x.current_balance || 0).toLocaleString('en-IN')}</option>)}</select>{selectedAccount && <span className="account-balance"><b>{selectedAccount.name}</b><span>Current balance · ₹{Number(selectedAccount.current_balance || 0).toLocaleString('en-IN')}</span></span>}</label>
    {isTransfer ? <><label>To account<select required name="destinationAccountId" value={form.destinationAccountId || ''} onChange={update}><option value="">Select account</option>{activeAccounts.filter(x => x.id !== form.accountId).map(x => <option key={x.id} value={x.id}>{x.icon} {x.name} · ₹{Number(x.current_balance || 0).toLocaleString('en-IN')}</option>)}</select></label><label>Notes<textarea name="note" value={form.note || ''} onChange={update} rows="2" placeholder="Example: Move money to savings" /></label></> : <>
      <label>Category<select name="category" value={form.category} onChange={update}>{categories.map(x => <option key={x}>{x}</option>)}</select></label><div className="category-chips" aria-label="Frequently used categories">{quickCategories.map(category => <button type="button" className={form.category === category ? 'selected' : ''} key={category} onClick={() => setForm(x => ({ ...x, category }))}>{category}</button>)}</div><label>Notes<textarea name="note" value={form.note || ''} onChange={update} rows="2" placeholder="Example: Lunch with friends" /></label><button className="more-details-toggle" type="button" aria-expanded={moreDetails} onClick={() => setMoreDetails(x => !x)}>{moreDetails ? '▲' : '▼'} More Details</button>
      {moreDetails && <div className="more-details"><label>Payment method<select name="paymentMethod" value={form.paymentMethod || ''} onChange={update}>{methods.map(x => <option key={x}>{x}</option>)}</select></label><label>Merchant<input name="merchant" value={form.merchant || ''} onChange={update} placeholder="e.g. Swiggy" /></label><label>Location<input name="location" value={form.location || ''} onChange={update} placeholder="e.g. Koramangala" /></label><label>Tags<input name="tags" value={Array.isArray(form.tags) ? form.tags.join(', ') : form.tags} onChange={update} placeholder="food, work (comma separated)" /></label><label>Receipt upload<input type="file" accept="image/*" onChange={upload} />{form.receiptPath && <small>Receipt attached</small>}</label><label>Recurring<select name="recurringFrequency" value={form.recurringFrequency || ''} onChange={update}><option value="">Not recurring</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label></div>}
    </>}
    {formError && <p className="form-error">{formError}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={saving} className="primary">{saving ? 'Saving…' : isTransfer ? 'Save transfer' : 'Save expense'}</button></div>
  </form></div>
}
